
# Gem::Specification for Stringray-2
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: stringray
version: !ruby/object:Gem::Version 
  version: "2"
platform: ruby
authors: 
- elliottcable
autorequire: 
bindir: bin

date: 2008-08-15 00:00:00 -08:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: Combining many of the benefits of Arrays and Strings, StringRay allows you to treat a String as an Array of words in many cases.
email: 
- StringRay@elliottcable.com
executables: []

extensions: []

extra_rdoc_files: 
- lib/stringray.rb
- README.mkdn
files: 
- lib/stringray.rb
- Rakefile
- README.mkdn
- spec/stringray_spec.rb
- .manifest
- StringRay.gemspec
has_rdoc: true
homepage: http://github.com/elliottcable/stringray
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- StringRay
- --main
- README.mkdn
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: stringray
rubygems_version: 1.2.0
specification_version: 2
summary: Combining many of the benefits of Arrays and Strings, StringRay allows you to treat a String as an Array of words in many cases.
test_files: []
